# Generated by Django 5.2.4 on 2025-08-16 14:34

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('events', '0004_event_max_attendees'),
    ]

    operations = [
        migrations.CreateModel(
            name='Bracelet',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag_uid', models.CharField(max_length=128, unique=True)),
                ('active', models.BooleanField(default=True)),
                ('issued_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('reservation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='bracelet', to='events.reservation')),
            ],
        ),
    ]
